# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('ua', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(default='LittlePanger', max_length=32)),
                ('name_href', models.CharField(default='#', max_length=100)),
                ('content_img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=100)),
                ('fa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=100)),
                ('header_subtitle', models.CharField(max_length=100, null=True)),
                ('header_img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=15)),
            ],
        ),
    ]
