# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='index',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
