# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190822_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='filename',
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(default='/', upload_to='md'),
        ),
    ]
