# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190822_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(default='/', upload_to='md')),
                ('url', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(default='LittlePanger', max_length=32)),
                ('name_href', models.CharField(default='/', max_length=100)),
                ('content_img', models.ImageField(upload_to='img')),
                ('is_show', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
