# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-22 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190822_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 20, 57, 5, 17787)),
        ),
    ]
