# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190823_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='city',
            field=models.CharField(default='Beijing', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='country',
            field=models.CharField(default='China', max_length=20),
        ),
    ]
