# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190823_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='browser',
            field=models.CharField(default='Chrome', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='system',
            field=models.CharField(default='Windows10', max_length=30),
        ),
    ]
